Nestor/Nestor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='jobs/', permanent=True)),
    path('admin/', admin.site.urls),
    path('applicants/', include('applicant.urls')),
    path('companies/', include('company.urls')),
    path('jobs/', include('job.urls')),
    path('user/', include('user.urls'))
]

Nestor/job/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='job_index'),
    path('<int:id>', views.get_job_by_id, name="job_page"),
    path('create_job', views.create_job, name="create_job"),
    path('favorite_jobs', views.favorite_jobs, name="favorite_jobs"),
    path('applied_jobs', views.applied_jobs, name="applied_jobs"),
    path('favorite_job', views.favorite_job, name="favorite_job"),
    path('your_job_offers', views.your_job_offers, name="your_job_offers"),
    path('your_job_offers/<int:id>', views.get_applications_by_job_id, name="applications_page"),
    path('your_job_offers/<int:jid>/application/<int:aid>', views.review_application, name="review_application"),
]

Nestor/common/models.py
from django.db import models


class Country(models.Model):
    '''List of Countries'''
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


class City(models.Model):
    '''List of Cities with reference to their respective Countries'''
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


class ZipCode(models.Model):
    '''List of ZipCodes with reference to their respective Cities'''
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    zip = models.CharField(max_length=20)

    def __str__(self):
        return str(self.city) + " " + str(self.zip)


class SkillGenre(models.Model):
    '''List of all Skill Genres
    genres: Programming Languages, Languages, Outdoor Activites, Sports, Liscenses, Hobbies'''
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


class Skills(models.Model):
    '''List of all Skills with reference to their respective Genre
    i.e. name: Python -> genre: Programming Language'''
    genre = models.ForeignKey(SkillGenre, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


class JobCategory(models.Model):
    '''List of all Job Categories'''
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)

Nestor/job/models.py
from django.db import models
from company.models import Company
from common.models import ZipCode, Skills, JobCategory
from applicant.models import Applicant, Experience, Education, References
from django.utils import timezone
from django.contrib.auth.models import User


class JobType(models.Model):
    '''Class that contains a list of all type of jobs
    Types: summer/internship/part-time/fulltime'''
    type = models.CharField(max_length=100)

    def __str__(self):
        return str(self.type)


class Job(models.Model):
    '''Class that contains all the data for all job offers'''
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    zipcode = models.ForeignKey(ZipCode, on_delete=models.SET_NULL, null=True)
    job_type = models.ForeignKey(JobType, on_delete=models.SET_NULL, null=True)
    job_category = models.ForeignKey(JobCategory, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100)
    job_image = models.CharField(max_length=9999, blank=True, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    date_of_offering = models.DateField(default=timezone.now)
    application_due_date = models.DateField()
    starting_date = models.DateField()
    num_of_applicants = models.IntegerField(default=0)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return str(self.name) + ", " + self.company.name


class Application(models.Model):
    '''Class that contains all application-specific applicant data'''
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    cover_letter = models.TextField(max_length=1000, blank=True, null=True)
    is_submitted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.applicant.full_name) + ' - ' + str(self.job.name)


class FavoriteJob(models.Model):
    '''Class that connects a user to a job
    This connection means that the user has favorited that job'''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user.get_full_name()) + ' - ' + str(self.job.name)


class hasSkills(models.Model):
    '''Class that connects a user's application to a skill'''
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skills, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.application.applicant.full_name) + ' - ' + str(self.skill.name)


class hasExperience(models.Model):
    '''class that connects a user's application to an experience'''
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    experience = models.ForeignKey(Experience, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.application.applicant.full_name) + ' - ' + str(self.experience.workplace_name) + str(self.experience.role)


class hasEducation(models.Model):
    '''Class that connects a user's application to an education'''
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    education = models.ForeignKey(Education, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.application.applicant.full_name) + ' - ' + str(self.education.school_name) + str(self.education.degree)


class hasReferences(models.Model):
    '''class that connects a user's application to a reference'''
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    reference = models.ForeignKey(References, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.application.applicant.full_name) + ' - ' + str(self.reference.name)

Nestor/job/views.py
from django.shortcuts import render, get_object_or_404, redirect
from job.forms.job_form import JobCreateForm
from job.models import Job, Application, FavoriteJob, hasEducation, hasExperience, hasReferences, hasSkills
from django.utils import timezone
from common.models import JobCategory, City
from company.models import Company, Employee
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required


def add_days_left(job):
    '''Adds the days left of a given job offer to the job card'''
    days_left = job.application_due_date - timezone.now().date()
    job.days_left = str(days_left).split()[0]
    return job


def index(request):
    '''renders the list of available jobs with the required data for
    each job's job card'''
    all_jobs = Job.objects.all().order_by('name')
    fav_jobs = ""
    employee = ""
    if request.user.is_authenticated: 
        fav_jobs = FavoriteJob.objects.filter(user=request.user).all()
        employee = Employee.objects.filter(user=request.user.id).first()
        fav_jobs = [job.job.id for job in fav_jobs]
    # Getting the query parameters
    job_param = request.GET.get('job')
    com_params = list(request.GET.getlist('com'))
    cou_params = list(request.GET.getlist('cou'))
    cat_params = list(request.GET.getlist('cat'))

    if job_param:
        all_jobs = all_jobs.filter(name__icontains=job_param)
    if com_params:
        all_jobs = all_jobs.filter(company__id__in=com_params)
    if cou_params:
        all_jobs = all_jobs.filter(zipcode__city_id__in=cou_params)
    if cat_params:
        all_jobs = all_jobs.filter(job_category_id__in=cat_params)

    jobs = [add_days_left(job) for job in all_jobs]
    filtered_jobs = [job for job in jobs if int(job.days_left) > 0]

    context = {'jobs': filtered_jobs,
               'active_section': get_active_section(request),
               'countries': City.objects.all().order_by('name'),
               'companies': Company.objects.all().order_by('name'),
               'categories': JobCategory.objects.all().order_by('name'),
               'countries_checked': [int(param_id) for param_id in cou_params],
               'countries_placeholder':
                   ', '.join([city.name for city in City.objects.filter(id__in=cou_params).order_by('name')]),
               'categories_checked': [int(param_id) for param_id in cat_params],
               'categories_placeholder':
                   ', '.join([cat.name for cat in JobCategory.objects.filter(id__in=cat_params).order_by('name')]),
               'companies_checked': [int(param_id) for param_id in com_params],
               'companies_placeholder':
                   ', '.join([com.name for com in Company.objects.filter(id__in=com_params).order_by('name')]),
               'job_value': job_param or "",
               'fav_jobs': fav_jobs,
               'employee': employee
               }

    return render(request, 'job/index.html', context)


def get_application_status(application):
    '''updates a job's application status with regard to the deadline
    of its application_due_date
    If an employee of the company has made the job unavailable, then
    the status changes to "finished"'''
    if application.job.application_due_date < timezone.now().date():
        if not application.job.is_available:
            application.status = 'Finished'
        else:
            application.status = 'In review'
    else:
        application.status = 'In progress'


def get_job_by_id(request, id):
    '''renders a specific job's page with all relevant information'''
    fav_jobs = FavoriteJob.objects.filter(user_id=request.user.id).all()
    application = Application.objects.filter(applicant__user_id=request.user.id, job_id=id).first()
    employee = Employee.objects.filter(user=request.user.id).first()

    if application:
        get_application_status(application)

    return render(request, 'job/job_page.html', {
        'job': get_object_or_404(Job, pk=id),
        'fav_jobs': [job.job.id for job in fav_jobs],
        'application': application,
        'employee': employee,
        'active_section': get_active_section(request)
    })



@login_required(redirect_field_name="/login")
@permission_required('job.add_job', raise_exception=True)
def create_job(request):
    '''A user that is assigned as an employee can create a job
    for the specific company that he is registered with'''
    employee = Employee.objects.filter(user=request.user).first()
    active_section = get_active_section(request)
    if request.method == 'POST':
        form = JobCreateForm(data=request.POST, initial= {'company': employee.company})
        if form.is_valid():
            job = form.save(commit=False)
            job.company = employee.company
            job.save()
            return redirect('job_index')
    else:
        form = JobCreateForm()
    return render(request, 'job/create_job.html', {
        'form': JobCreateForm(data=request.POST),
        'employee': employee,
        'active_section': active_section
    })


@login_required(redirect_field_name="/login")
def favorite_jobs(request):
    '''Renders a list of all the jobs that the user has favorited'''
    fav_jobs = FavoriteJob.objects.filter(user_id=request.user.id).all()
    job_ids = [app.job_id for app in fav_jobs]
    all_jobs = Job.objects.filter(id__in=job_ids)

    context = {'companies': Company.objects.all().order_by('name'),
               'categories': JobCategory.objects.all().order_by('name'),
               'countries': City.objects.all().order_by('name'),
               'jobs': [add_days_left(job) for job in all_jobs],
               'active_section': get_active_section(request),
               'fav_jobs': [job.job.id for job in fav_jobs]}

    return render(request, 'job/favorite_jobs.html', context)


@login_required(redirect_field_name="/login")
def applied_jobs(request):
    '''Renders a list of all the jobs that the user has applied to'''
    applications = Application.objects.filter(applicant__user_id=request.user.id, is_submitted=True).all()

    for application in applications:
        get_application_status(application)

    context = {'companies': Company.objects.all().order_by('name'),
               'categories': JobCategory.objects.all().order_by('name'),
               'countries': City.objects.all().order_by('name'),
               'applications': applications,
               'active_section': get_active_section(request)}

    return render(request, 'job/applied_jobs.html', context)


@login_required(redirect_field_name="/login")
def favorite_job(request):
    '''Adds the specified job to the favorited jobs list'''
    # To get the job that was selected in the url before and the applicant
    job_id = request.POST.get('job_id')

    fav_jobs = FavoriteJob.objects.filter(user_id=request.user.id).all()
    fav_job = fav_jobs.filter(job__id=job_id).all()
    job = get_object_or_404(Job, id=job_id)

    if not fav_job:
        new_favorite = FavoriteJob(user=request.user, job=job)
        new_favorite.save()
    else:
        fav_job.delete()

    return redirect(f'/jobs/{job_id}')


@login_required(redirect_field_name="/login")
@permission_required('job.view_job', raise_exception=True)
def your_job_offers(request):
    '''Renders a list of all jobs that a given company has on offer'''
    employee = get_object_or_404(Employee, user=request.user)
    company_id = employee.company.id
    company_jobs = Job.objects.filter(company_id=company_id)
    get_total_applicants(company_jobs)

    context = {'jobs': [add_days_left(job) for job in company_jobs],
               'active_section': get_active_section(request),
               'employee': employee}

    return render(request, 'job/your_job_offers.html', context)

@login_required(redirect_field_name="/login")
@permission_required('job.view_job', raise_exception=True)
def get_applications_by_job_id(request, id):
    '''renders a list of all applicants that have applied to a
    job that the company has offered'''
    employee = get_object_or_404(Employee, user=request.user)
    job = get_object_or_404(Job, pk=id)
    applications = Application.objects.filter(job_id=id).all()
    job.num_of_applicants = len(applications)

    for application in applications:
        education = hasEducation.objects.filter(application=application.id)
        experience = hasExperience.objects.filter(application=application.id)
        if education.exists():
            for ed in education:
                application.education = ed.education

        if experience.exists():
            for ex in experience:
                application.experience = ex.experience

    return render(request, 'job/applications_page.html', {
        'job': job,
        'applications':applications,
        'active_section': get_active_section(request),
        'employee': employee
    })

@permission_required('job.view_job', raise_exception=True)
def review_application(request, jid, aid):
    '''renders an applicants application for an employee that is
    looking to hire him'''
    employee = get_object_or_404(Employee, user=request.user)
    application = Application.objects.get(id=aid)

    education = hasEducation.objects.filter(application=application.id)
    experience = hasExperience.objects.filter(application=application.id)
    skills = hasSkills.objects.filter(application=application.id)
    references = hasReferences.objects.filter(application=application.id)
    if education.exists():
        application.education = []
        for ed in education:
            application.education.append(ed.education)

    if experience.exists():
        application.experience = []
        for ex in experience:
            application.experience.append(ex.experience)

    if skills.exists():
        application.skills = []
        for skill in skills:
            application.skills.append(skill.skill)
    
    if references.exists():

Nestor/templates/job/applicant_card.html
{% load static %}
    {% block additionalStyles %}
    <link rel="stylesheet" href="{% static "css/applicant_card.css" %}"/>
    {% endblock %}
    <a href="/jobs/your_job_offers/{{ job.id }}/application/{{ application.id }}" class="app_card">
        <div class="app_image_container">
            <img src="{{ application.applicant.profile_image }}" alt="profile image">
        </div>
        <div class="app_card_info">
            <p>{{ application.applicant.full_name }}</p>
            <p>{{ application.education.school_name }} - {{ application.education.level }}</p>
            <p>{{ application.experience.workplace_name }} - {{ application.experience.role }}</p>

        </div>
        <div class="app_card_info">
            <div class="info_container"><img src="{% static 'images/phone.png' %}" alt=""><p>{{ application.applicant.phone }}</p></div>
            <div class="info_container"><img src="{% static 'images/location.png' %}" alt=""><p>{{ application.applicant.address }}</p></div>
            <div class="info_container"><img src="{% static 'images/mail_icon.png' %}" alt=""><p>{{ application.applicant.email }}</p></div>
        </div>
    </a>

Nestor/templates/job/applications_page.html
{% extends 'base.html' %}
{% load static %}
    {% block additionalStyles %}
    <link rel="stylesheet" href="{% static 'css/applications_page.css' %}"/>
    <link rel="stylesheet" href="{% static "css/applicant_card.css" %}"/>
    {% endblock %}
    {% block content %}
    <div class="job-page-container">
        <div class="job-details">
            <h1>{{ job.name }}</h1>
            <div class="description-container">
                <h3>Job description</h3>
                <p>{{ job.description }}</p>
            </div>
        </div>
        <div class="right-container">
            <h3>Due date</h3>
            <div class="other-info">
                <p>{{ job.application_due_date }}</p>
            </div>
            <h3>Category</h3>
            <div class="other-info">
                <p>{{ job.job_category }}</p>
            </div>
            <h3>Job type</h3>
            <div class="other-info">
                <p>{{ job.job_type }}</p>
            </div>
        </div>
    </div>
    <h3>Number of applicants: {{ job.num_of_applicants }}</h3>
    <div class="all_applicants">
        {% for application in applications %}
            {% include 'job/applicant_card.html' with application=application %}
        {% endfor %}
    </div>
    {% endblock %}

Nestor/templates/job/applied_jobs.html
{% extends "job/index.html" %}
{% load static %}
{% block additionalStyles %}
    <link rel="stylesheet" href="{% static 'css/job_cards.css' %}" />
{% endblock additionalStyles %}
{% block content %}
    {% if applications %}
    <div id="all-jobs" class="all_jobs">
        {% for application in applications %}
            {% include 'job/single_applied_job.html' with application=application %}
        {% endfor %}
    </div>
    {% else %}
    <div class="no-data-found">
        <img src="{% static 'images/Nestor_logo.png'%}">
        <h2>No applied jobs</h2>
    </div>
    {% endif %}
{% endblock %}

Nestor/templates/job/create_job.html
{% extends "base.html" %}
{% load static %}
    {% block additionalStyles %}
    <link rel="stylesheet" href="{% static 'css/create_job.css' %}" />
    <script type="text/javascript" src="{% static 'js/create_job.js' %}"></script>
    {% endblock additionalStyles %}
    {% block content %}
    <div class="create-job-container">
        <h2 class="title">Create a new job offer for {{ employee.company }}</h2>
        <form class="form form-horizontal" action="{% url 'create_job' %}" method="post">
            {% csrf_token %}
            <div class="form-upper">
                <!-- <label for="id-job_image">Job image: </label> -->
                <div class="job-image-container">
                    <img id="job-image" src="{% static 'images/empty_img.png' %}" />                
                    <div id="image-input" class="image-input">
                        {{ form.job_image }}
                        <a id="update-image" class="submit-btn" onclick="update_image()">Display</a>
                    </div>
                    <p id="error-msg-image" class="error-msg hidden">Image URL not valid, please try again.</p>
                </div>

                <div class="middle-upper-form">
                    <label for="id_name">Job name: </label>
                    {{ form.name }}
                    <label for="id_category">Job category: </label>
                    {{ form.job_category }}
                    <label for="id_application_due_date">Due date: </label>
                    {{ form.application_due_date }}
                    <label for="id_starting_dage">Starting date: </label>
                    {{ form.starting_date }}
                </div>
                <div class="right-upper-form">
                    <!-- <label for="id_country">Country: </label> -->
                    <!-- {{ form.country }} -->
                    <!-- <label for="id_city">City: </label> -->
                    <!-- {{ form.city }} -->
                    <label for="id_zipcode">Zipcode: </label>
                    {{ form.zipcode }}
                    <label for="id_address">Address: </label>
                    {{ form.address }}
                    <label for="id_job_type">Job type: </label>
                    {{ form.job_type }}
{#                    <label for="id_percentage">Job percentage: </label>#}
{#                    {{ form.percentage }}#}
                </div>
            </div>
            <div class="desc-container">
                <label for="id_description">Description: </label>
                {{ form.description }}
            </div>
            <div id="temporary">
                <!-- <label for="id_company">Company: </label> -->
                <label for="id_is_available">Availability: </label>
                {{ form.is_available }}
            </div>
            <input type="submit" value="Create a new Job" class="submit-btn"/>
        </form>
    </div>
    {% endblock %}

Nestor/templates/job/favorite_jobs.html
{% extends "job/index.html" %}
{% load static %}
{% block additionalStyles %}
    <link rel="stylesheet" href="{% static 'css/job_cards.css' %}" />
{% endblock additionalStyles %}
{% block content %}
    {% if jobs %}
    <div id="all-jobs" class="all_jobs">
        {% for job in jobs %}
            {% include 'job/single_job.html' with job=job %}
        {% endfor %}
    </div>
    {% else %}
    <div class="no-data-found">
        <img src="{% static 'images/Nestor_logo.png'%}">
        <h2>No favorite jobs</h2>
    </div>
    {% endif %}
{% endblock %}

Nestor/templates/job/index.html
{% extends 'base.html' %}
{% load static %}
{% block additionalStyles %}
        <link rel="stylesheet" href="{% static 'css/job_cards.css' %}" />
{% endblock additionalStyles %}
{% block content %}
    {% include 'job/searchbar.html' %}    
    {% if jobs %}
    <div id="all-jobs" class="all_jobs">
        {% for job in jobs %}
            {% include 'job/single_job.html' with job=job %}
        {% endfor %}
    </div>
    {% else %}
    <div class="no-data-found">
        <img src="{% static 'images/Nestor_logo.png'%}" alt="logo">
        <h2>No jobs found, try editing your search</h2>
    </div>
    {% endif %}
{% endblock %}

Nestor/templates/job/job_page.html
{% extends 'base.html' %}
{% load static %}
{% block additionalStyles %}
<link rel="stylesheet" href="{% static 'css/job_page.css' %}"/>
{% endblock %}
{% block content %}
<div class="job-page-container">
    <div class="job-page-content">
        <div class="left-job-view">
            {% if job.job_image %}
            <img class="job-image" src="{{ job.job_image }}" class="job-img"/>
            {% else %}
            <img class="job-image" src="{% static 'images/Nestor_logo.png' %}" class="job-img"/>
            {% endif %}
            <div class="left-job-info">
                <h5>Due Date</h5>
                <p>{{ job.application_due_date }}</p>
                <h5>Starting Date</h5>
                <p>{{ job.starting_date }}</p>
                <h5>Category</h5>
                <p>{{ job.job_category.name }}</p>
                <h5>Job type</h5>
                <p>{{ job.job_type }}</p>
                <h5>Location</h5>
                <p>{{ job.zipcode.city }}, {{ job.zipcode.city.country }} </p>
            </div>
        </div>
        <div class="middle-job-view">
            <div class="title-and-btn">
                <h2 class="job-title">{{ job.name }}</h2>
                {% if not application.is_submitted and not employee %}
                    <a class="apply-btn" href="/applicants/application/{{ job.id }}/cover-letter">Apply</a>
                {% endif %}
            </div>
            {% if application.is_submitted %}
                <div>
                    <p>You applied {{ application.date }}</p>
                    <p>Status: {{ application.status }}</p>
                </div>
            {% endif %}
            {% if not employee %}
            <form action="{% url 'favorite_job' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="job_id" value="{{ job.id }}">
                <button class="favorite-btn">
                    {% if job.id in fav_jobs %}
                        <p>Remove from favorites</p>
                        <img class="heart-image" src="{% static 'images/filled_heart.png'%}" alt="">
                    {% else %}
                        <p>Add to favorites</p>
                        <img class="heart-image" src="{% static 'images/heartoutline_110866.png'%}" alt="">
                    {% endif %}
                </button>
            </form>
            {% endif %}
            <h5>Job description</h5>
            <p>{{ job.description }}</p>
        </div>
        <div class="right-job-view">
            <img class="company-logo" src="{{ job.company.logo }}" />
            <div class="company-btn-container">
                <h3 class="company-title">{{ job.company.name }}</h3>
                <div class="company-page-btn-container">
                    <a class="company-page-btn" href="/companies/{{ job.company.id }}">Company page </a>
                </div>
            </div>
            <h5>About us</h5>
                <p class="company-description">{% autoescape off %}{{ job.company.description }}{% endautoescape %}</p>
            <h5>Address</h5>
            <p>{{ job.company.address }}, {{ job.company.zipcode.city }}, {{ job.company.zipcode.city.country }} </p>
            <h5>Employees</h5>
            <p>{{ job.company.number_of_employees }}</p>
        </div>
    </div>
</div>
{% endblock %}

Nestor/templates/job/review_application.html
{% extends 'base.html' %}
{% load static %}
    {% block additionalStyles %}
<link rel="stylesheet" href="{% static "css/review_application.css" %}"/>
{% endblock %}
{% block content %}    

<div class="application-container">
    <div class="left-application">
        <div class="image-container">
            <img class="profile-image" src="{{ application.applicant.profile_image }}" alt="profile image"/>
        </div>
        <div class="basic-info-section">
            <h4>Basic info</h4>
            <div class="basic-info-item">
                <img class="icon" src="{% static 'images/phone_icon.png' %}"/>
                <span>{{ application.applicant.phone }}</span>
            </div>
            <div class="basic-info-item">
                <img class="icon" src="{% static 'images/location.png' %}"/>
                <span>{{ application.applicant.zipcode.city.name }}, {{ application.applicant.zipcode.city.country.name }} </span>
            </div>
            <div class="basic-info-item">
                <img class="icon" src="{% static 'images/mail_icon.png' %}"/>
                <span>{{ application.applicant.email }} </span>
            </div>
        </div>
        {% if application.references %}
        <div class="info-section">
            <h4>References</h4>
            {% for item in application.references %}
            <div class="info-item">
                <p>{{ item.name }}</p>
                <ul>
                    <li>{{ item.role }} - {{ item.workplace_name }}</li>
                    <li>{{ item.email }}</li>
                    {% if item.is_contactable %}
                    <li>Is contactable: Yes</li> 
                    {% else %}
                    <li>Is contactable: No</li> 
                    {% endif %}

            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% if application.skills %}
        <div class="info-section">
            <h4>Skills</h4>
            <ul class="info-item">
                {% for item in application.skills %}
                <li>{{ item.name }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
    <div class="right-application">
        <h1 class="title-name">{{ application.applicant.full_name }}</h1>
        <p>{{ application.applicant.bio }}</p>
        {% if application.experience %}
        <div class="info-section">
            <h4>Experience</h4>
            {% for item in application.experience  %}
            <div class="info-item">
                <p>{{ item.role }} - {{ item.workplace_name }}</p>
                <ul>
                    {% if item.end_date %}
                    <li>{{ item.start_date }} - {{ item.end_date }}</li>
                    {% else %}
                    <li>{{ item.start_date }} - currently</li>
                    {% endif %}
                    <li>{{ item.description }}</li>
                </ul>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% if application.education %}
        <div class="info-section">
            <h4>Education</h4>
            {% for item in application.education %}
            <div class="info-item">
                <p>{{ item.school_name }}</p>
                <p>{{ item.degree }} {{ item.level }}</p>
                <ul>
                    {% if item.end_date %}
                    <li>{{ item.start_date }} - {{ item.end_date }}</li>
                    {% else %}
                    <li>{{ item.start_date }} - currently</li>
                    {% endif %}
                </ul>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <div class="info-section">
            <h4>Cover Letter</h4>
            <p>{{ application.cover_letter }}</p>
        </div>

    </div>
</div>
{% endblock %}