Nestor/Nestor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='jobs/', permanent=True)),
    path('admin/', admin.site.urls),
    path('applicants/', include('applicant.urls')),
    path('companies/', include('company.urls')),
    path('jobs/', include('job.urls')),
    path('user/', include('user.urls'))
]

Nestor/applicant/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='applicant_index'),
    path('applicant', views.applicant, name='applicant'),
    path('applicant/contact-info', views.contact_info, name='applicant/contact-info'),
    path('application/contact-info/<int:id>', views.application_contact_info, name='application/contact-info'),

    path('applicant/experience_add', views.experience_add, name='applicant/experience_add'),
    path('applicant/education_add', views.education_add, name='applicant/education_add'),
    path('applicant/reference_add', views.reference_add, name='applicant/reference_add'),
    path('applicant/add_skill', views.add_skill, name='applicant/add_skill'),

    path('applicant/experience_edit', views.experience_edit, name='applicant/experience_edit'),
    path('applicant/education_edit', views.education_edit, name='applicant/education_edit'),
    path('applicant/reference_edit', views.reference_edit, name='applicant/reference_edit'),

    path('applicant/remove_skill', views.remove_skill, name='applicant/remove_skill'),
    path('applicant/remove_experience', views.remove_experience, name='applicant/remove_experience'),
    path('applicant/remove_education', views.remove_education, name='applicant/remove_education'),
    path('applicant/remove_reference', views.remove_reference, name='applicant/remove_reference'),

    path('application/<int:id>/<str:page>', views.apply_init, name='apply/init'),
    path('application/experience_add/<int:id>', views.application_experience_add, name='application/experience_add'),
    path('application/education_add/<int:id>', views.application_education_add, name='application/education_add'),
    path('application/reference_add/<int:id>', views.application_reference_add, name='application/reference_add'),
    path('application/add_skill/<int:id>', views.application_add_skill, name='application/add_skill'),

    path('application/experience_edit/<int:id>', views.application_experience_edit, name='application/experience_edit'),
    path('application/education_edit/<int:id>', views.application_education_edit, name='application/education_edit'),
    path('application/reference_edit/<int:id>', views.application_reference_edit, name='application/reference_edit'),
    path('application/cover-letter/<int:id>', views.application_cover_letter, name='application/cover-letter'),

    path('application/remove_skill/<int:id>', views.application_remove_skill, name='application/remove_skill'),
    path('application/remove_experience/<int:id>', views.application_remove_experience, name='application/remove_experience'),
    path('application/remove_education/<int:id>', views.application_remove_education, name='application/remove_education'),
    path('application/remove_reference/<int:id>', views.application_remove_reference, name='application/remove_reference'),

    path('application/apply/<int:id>', views.final_apply, name='final_apply')
]

Nestor/job/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='job_index'),
    path('<int:id>', views.get_job_by_id, name="job_page"),
    path('create_job', views.create_job, name="create_job"),
    path('favorite_jobs', views.favorite_jobs, name="favorite_jobs"),
    path('applied_jobs', views.applied_jobs, name="applied_jobs"),
    path('favorite_job', views.favorite_job, name="favorite_job"),
    path('your_job_offers', views.your_job_offers, name="your_job_offers"),
    path('your_job_offers/<int:id>', views.get_applications_by_job_id, name="applications_page"),
    path('your_job_offers/<int:jid>/application/<int:aid>', views.review_application, name="review_application"),
]

Nestor/applicant/models.py
from django.db import models
from django.contrib.auth.models import User
from common.models import Skills, ZipCode


class Applicant(models.Model):
    '''Class conatining all data for all users'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=70)
    profile_image = models.CharField(max_length=9999)
    email = models.EmailField()
    phone = models.CharField(max_length=7)
    zipcode = models.ForeignKey(ZipCode, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=120)
    bio = models.CharField(max_length=400, null=True)

    def __str__(self):
        return str(self.user.get_full_name())


class CVSkills(models.Model):
    '''Class that connects a user's profile to a specific Skill in our
    skill list'''
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skills, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.applicant) + ": " + str(self.skill.name) 
    

class Experience(models.Model):
    '''Class that contains all data for an input instance of "Experience"'''
    workplace_name = models.CharField(max_length=255)
    role = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    description = models.CharField(max_length=9999, blank=True, null=True)

    def __str__(self):
        return str(self.workplace_name) + " - " + str(self.role) + " - " + str(self.start_date)


class CVExperience(models.Model):
    '''Class that connects a specific Experience to a specific applicant'''
    experience = models.ForeignKey(Experience, on_delete=models.CASCADE)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.applicant.full_name) + " - " + str(self.experience.workplace_name)


class EducationLevel(models.Model):
    '''CLass that contains a list of all education levels'''
    level = models.CharField(max_length=255)

    def __str__(self):
        return self.level


class Education(models.Model):
    '''Class that contains all data for an input instance of "Education"'''
    school_name = models.CharField(max_length=255)
    degree = models.CharField(max_length=255)
    level = models.ForeignKey(EducationLevel, on_delete=models.SET_NULL, null=True)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    description = models.CharField(max_length=9999, blank=True, null=True)

    def __str__(self):
        return str(self.school_name) + " " + str(self.degree) + " " + str(self.level) + " " + str(self.start_date)


class CVEducation(models.Model):
    '''Class that connects a specific instance of Education to a specific applicant'''
    education = models.ForeignKey(Education, on_delete=models.CASCADE)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.applicant.full_name) + ' - ' + str(self.education.degree) + ' - ' + str(self.education.level)

class References(models.Model):
    '''Class that contains all data for an input instance of "Reference"'''
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=20)
    workplace_name = models.CharField(max_length=255)
    role = models.CharField(max_length=255)
    is_contactable = models.BooleanField()

    def __str__(self):
        return str(self.name) + " " + str(self.role)


class CVReferences(models.Model):
    '''Class that coonnects a specific reference to a specific applicant'''
    reference = models.ForeignKey(References, on_delete=models.CASCADE)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.applicant.full_name) + ' - ' + str(self.reference.name)

Nestor/applicant/forms/applicant_form.py
from django.forms import ModelForm, widgets
from applicant.models import *


class ApplicantForm(ModelForm):
    '''Class containing the form to create a new applicant'''
    class Meta:
        model = Applicant
        exclude = ['id', 'user']
        widgets = {
                'profile_image': widgets.TextInput(attrs={'class': 'form-control'})
        }


class ExperienceForm(ModelForm):
    '''Class containing the form to create a new experience'''
    class Meta:
        model = Experience
        exclude = ['id']
        widgets = {
            'workplace_name': widgets.TextInput(attrs={'class': 'form-control'}),
            'role': widgets.TextInput(attrs={'class': 'form-control'}),
            'start_date': widgets.DateInput(attrs={'class': 'form-control'}),
            'end_date': widgets.DateInput(attrs={'class': 'form-control'}),
            'description': widgets.Textarea(attrs={'class': 'form-control'})
        }


class CVExperienceForm(ModelForm):
    '''Class containing the form to connects a user with an experience'''
    class Meta:
        model = CVExperience
        fields = ['applicant', 'experience']


class EducationForm(ModelForm):
    '''Class containing the form to create a new education'''
    class Meta:
        model = Education
        exclude = ['id']
        widgets = {
            'school_name': widgets.TextInput(attrs={'class': 'form-control'}),
            'degree': widgets.TextInput(attrs={'class': 'form-control'}),
            'level': widgets.TextInput(attrs={'class': 'form-control'}),
            'start_date': widgets.DateInput(attrs={'class': 'form-control'}),
            'end_date': widgets.DateInput(attrs={'class': 'form-control'}),
            'description': widgets.Textarea(attrs={'class': 'form-control'})
        }


class CVEducationForm(ModelForm):
    '''Class containing the form to connects a user with an education'''
    class Meta:
        model = CVEducation
        fields = ['applicant', 'education']


class ReferenceForm(ModelForm):
    '''Class containing the form to create a new reference'''
    class Meta:
        model = References
        exclude = ['id']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'email': widgets.EmailInput(attrs={'class': 'form-control'}),
            'phone': widgets.TextInput(attrs={'class': 'form-control'}),
            'workplace_name': widgets.TextInput(attrs={'class': 'form-control'}),
            'role': widgets.TextInput(attrs={'class': 'form-control'}),
            'is_contactable': widgets.CheckboxInput(attrs={'class': 'checkbox'})
        }


class CVReferenceForm(ModelForm):
    '''Class containing the form to connects a user with a reference'''
    class Meta:
        model = CVReferences
        fields = ['applicant', 'reference']

Nestor/templates/applicant/VirtualCV/contact_info_edit.html
{% load static %}
<div class="contact-info hidden" id="contact-info/edit">
    <form class="form form-horizontal" method="post" action="applicant/contact-info">
        {% csrf_token %}
        <div class="horizontal-input">
            <h3>Contact Information</h3>
            <input type="submit" class="edit-button" value="Update" />
        </div>
        <div class="horizontal-input">
            <div class="profile-data-block">
                <p class="profile-data-label">Full name</p>
                <input type="text" name="full_name" class="profile-data-input" value="{{ applicant.full_name }}" required id="id_full_name">
            </div>
            <div class="profile-data-block">
                <p class="profile-data-label">Profile Picture</p>
                <input type="text" name="profile_image" class="profile-data-input form-control" value="{{ applicant.profile_image }}" required id="id_profile_image">
            </div>
        </div>

        <div class="horizontal-input">
            <div class="profile-data-block">
                <p class="profile-data-label">Email</p>
                <input type="text" name="email" class="profile-data-input" value="{{ applicant.email }}" required id="id_email">
            </div>
            <div class="horizontal-input date-input">
                <div class="profile-data-block">
                    <p class="profile-data-label">Country</p>
                    <select id="country-dropdown" class="profile-data-select">
                        <option value="" selected>Choose a country</option>
                        {% for country in countries %}
                        <option value={{ country.id }}>{{ country.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="profile-data-block">
                    <p class="profile-data-label">Zipcode</p>
                    <select name="zipcode" class="profile-data-select" required id="id_zipcode">
                        {% for option in zip_options %}
                        <option value="{{ option.id }}" data-country="{{ option.city.country.id }}">{{ option }}</option>
                        {% endfor %}
                        <option value="{{ applicant.zipcode.id  }}" selected>{{ applicant.zipcode }}</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="horizontal-input">
            <div class="profile-data-block">
                <p class="profile-data-label">Phone number</p>
                <input type="text" name="phone" class="profile-data-input" value="{{ applicant.phone }}" required id="id_phone">
            </div>
            <div class="profile-data-block">
                <p class="profile-data-label">Address</p>
                <input type="text" name="address" class="profile-data-input" value="{{ applicant.address }}" required id="id_address">
            </div>
        </div>

        <div class="hide-overflow">
            <p class="profile-data-label">Bio</p>
            <textarea name="bio" required id="id_bio" class="profile-data-input bio-input">{{ applicant.bio }}</textarea>
        </div>
    </form>
</div>

Nestor/templates/applicant/VirtualCV/contact_info_view.html
{% load static %}
<div class="contact-info" id="contact-info/view">

    <div class="horizontal-input">
        <h3>Contact Information</h3>
        <button onclick="toggleEditContactInfo()" class="edit-button">edit</button>
    </div>
    <div class="horizontal-input">
        <div class="profile-data-block">
            <p class="profile-data-label">Full name</p>
            <p class="profile-data">{{ applicant.full_name }}</p>
        </div>
        <div class="profile-data-block">
            <p class="profile-data-label">Country</p>
            <p class="profile-data">{{ applicant.zipcode.city.country}}</p>
        </div>
    </div>

    <div class="horizontal-input">
        <div class="profile-data-block">
            <p class="profile-data-label">Email</p>
            <p class="profile-data">{{ applicant.email }}</p>
        </div>
        <div class="profile-data-block">
            <p class="profile-data-label">City, zipcode</p>
            <p class="profile-data">{{ applicant.zipcode }}</p>
        </div>
    </div>

    <div class="horizontal-input">
        <div class="profile-data-block">
            <p class="profile-data-label">Phone number</p>
            <p class="profile-data">{{ applicant.phone }}</p>
        </div>
        <div class="profile-data-block">
            <p class="profile-data-label">Address</p>
            <p class="profile-data">{{ applicant.address }}</p>
        </div>
    </div>

    <div>
        <p class="profile-data-label">Bio</p>
        {% autoescape off %}{{ applicant.bio }}{% endautoescape %}
    </div>
</div>

Nestor/templates/applicant/VirtualCV/education_edit.html
{% load static %}
<div class="black_block hidden" id="education/edit/{{ education.education_id }}">
    <form class="form form-horizontal" method="post" action="applicant/education_edit">
        {% csrf_token %}
        <input type="hidden" name="education_id" value="{{ education.education_id }}">
        <div class="btn-container">
        <input type="submit" class="edit-button" value="Add" />
        </div>
        <div class="horizontal-input">
            <div class="profile-data-block-three">
                <p class="profile-data-label">School</p>
                <input type="text" name="school_name" value="{{ education.education.school_name }}" class="profile-data-input form-control" required id="id_school_name">
            </div>
            <div class="profile-data-block-three">
                <p class="profile-data-label">Degree</p>
                <input type="text" name="degree" value="{{ education.education.degree }}" class="profile-data-input form-control" required id="id_degree">
            </div>
            <div class="profile-data-block-three">
                <p class="profile-data-label">Level</p>
                <select name="level" class="profile-data-select" required id="id_level">
                    {% for option in education_levels %}
                    <option value="{{ option.id }}">{{ option }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="horizontal-input">
            <div class="profile-data-block">
                <p class="profile-data-label">Start Date</p>
                <input type="date" name="start_date" value="{{ education.education.start_date }}" class="profile-data-input form-control" required id="id_start_date">
            </div>
            <div class="profile-data-block">
                <p class="profile-data-label">End Date</p>
                <input type="date" name="end_date" value="{{ education.education.end_date }}" class="profile-data-input form-control" id="id_end_date">
            </div>
        </div>

        <div class="hide-overflow">
            <p class="profile-data-label">Degree Description</p>
            <textarea name="description" id="id_description" class="profile-data-input bio-input form-control">{{ education.education.description |safe }}</textarea>
        </div>
    </form>
</div>

Nestor/templates/applicant/VirtualCV/education_new.html
{% load static %}
<div class="black_block hidden" id="education/new">
    <form class="form form-horizontal" method="post" action="applicant/education_add">
        {% csrf_token %}
        <div class="btn-container">
            <input type="submit" class="edit-button" value="Add" />
        </div>
        <div class="horizontal-input">
        <div class="profile-data-block-three">
            <p class="profile-data-label">School</p>
            <input type="text" name="school_name" class="profile-data-input form-control" required id="id_school_name">
        </div>
        <div class="profile-data-block-three">
            <p class="profile-data-label">Degree</p>
            <input type="text" name="degree" class="profile-data-input form-control" required id="id_degree">
        </div>
        <div class="profile-data-block-three">
            <p class="profile-data-label">Level</p>
            <select name="level" class="profile-data-select" required id="id_level">
                {% for option in education_levels %}
                    <option value="{{ option.id }}">{{ option }}</option>
                {% endfor %}
            </select>
        </div>
        </div>

        <div class="horizontal-input">
        <div class="profile-data-block">
            <p class="profile-data-label">Start Date</p>
            <input type="date" name="start_date" class="profile-data-input form-control" required id="id_start_date">
        </div>
        <div class="profile-data-block">
            <p class="profile-data-label">End Date</p>
            <input type="date" name="end_date" class="profile-data-input form-control" id="id_end_date">
        </div>
        </div>

        <div class="hide-overflow">
            <p class="profile-data-label">Degree Description</p>
            <textarea name="description" id="id_description" class="profile-data-input bio-input form-control"></textarea>
        </div>
    </form>
</div>

Nestor/templates/applicant/VirtualCV/education_view.html
{% load static %}
<div class="black_block" id="education/view/{{ education.education_id }}">
    <form id="deleteForm" method="post" action="applicant/remove_education">
        {% csrf_token %}
        <div class="btn-container">
            <input type="hidden" name="education_id" value="{{ education.education_id }}">
            <button type="submit" class="remove-button">X</button>
        </div>
    </form>
    <button onclick="toggleEditEducation({{ education.education_id }})" class="edit-button">edit</button>
    <div class="horizontal-input">
    <div class="profile-data-block-three">
        <p class="profile-data-label">School</p>
        <p class="profile-data">{{ education.education.school_name }}</p>
    </div>
    <div class="profile-data-block-three">
        <p class="profile-data-label">Degree</p>
        <p class="profile-data">{{ education.education.degree }}</p>
    </div>
    <div class="profile-data-block-three">
        <p class="profile-data-label">Level</p>
        <p class="profile-data">{{ education.education.level }}</p>
    </div>
    </div>
    <div class="horizontal-input">
    <div class="profile-data-block">
        <p class="profile-data-label">Start date</p>
        <p class="profile-data">{{ education.education.start_date }}</p>
    </div>
    <div class="profile-data-block">
        <p class="profile-data-label">End date</p>
        <p class="profile-data">{{ education.education.end_date }}</p>
    </div>
    </div>

    <div class="hide-overflow">
        <p class="profile-data-label">Degree description</p>
        {% autoescape off %}{{ education.education.description }}{% endautoescape %}
    </div>
</div>

Nestor/templates/applicant/VirtualCV/experience_edit.html
{% load static %}
<div class="black_block hidden" id="experience/edit/{{ experience.experience_id }}">
    <form class="form form-horizontal" method="post" action="applicant/experience_edit">
        {% csrf_token %}
        <input type="hidden" name="experience_id" value="{{ experience.experience_id }}">
        <div class="btn-container">
            <input type="submit" class="edit-button" value="Update" />
        </div>
        <div class="horizontal-input">
            <div class="profile-data-block">
                <p class="profile-data-label">Company</p>
                <input type="text" name="workplace_name" class="profile-data-input form-control" value="{{ experience.experience.workplace_name }}" required id="id_workplace_name">
            </div>
            <div class="profile-data-block">
                <p class="profile-data-label">Role</p>
                <input type="text" name="role" class="profile-data-input form-control" value="{{ experience.experience.role }}" required id="id_role">
            </div>
        </div>

        <div class="horizontal-input">
            <div class="profile-data-block">
                <p class="profile-data-label">Start Date</p>
                <input type="date" name="start_date" class="profile-data-input form-control" value="{{ experience.experience.start_date }}" required id="id_start_date">
            </div>
            <div class="profile-data-block">
                <p class="profile-data-label">End Date</p>
                <input type="date" name="end_date" class="profile-data-input form-control" value="{{ experience.experience.end_date }}" id="id_end_date">
            </div>
        </div>

        <div class="hide-overflow">
            <p class="profile-data-label">Description</p>
            <textarea name="description" id="id_description" class="profile-data-input bio-input form-control">{{ experience.experience.description |safe }}</textarea>
        </div>
    </form>
</div>

Nestor/templates/applicant/VirtualCV/experience_new.html
{% load static %}
<div class="black_block hidden" id="experience/new">
    <form class="form form-horizontal" method="post" action="applicant/experience_add">
        {% csrf_token %}
        <div class="btn-container">
            <input type="submit" class="edit-button" value="Add" />
        </div>
    <div class="horizontal-input">
        <div class="profile-data-block">
            <p class="profile-data-label">Company</p>
            <input type="text" name="workplace_name" class="profile-data-input form-control" required id="id_workplace_name">
        </div>
        <div class="profile-data-block">
            <p class="profile-data-label">Role</p>
            <input type="text" name="role" class="profile-data-input form-control" required id="id_role">
        </div>
        </div>

    <div class="horizontal-input">
        <div class="profile-data-block">
            <p class="profile-data-label">Start Date</p>
            <input type="date" name="start_date" class="profile-data-input form-control" required id="id_start_date">
        </div>
        <div class="profile-data-block">
            <p class="profile-data-label">End Date</p>
            <input type="date" name="end_date" class="profile-data-input form-control" id="id_end_date">
        </div>
        </div>

        <div class="hide-overflow">
            <p class="profile-data-label">Description</p>
            <textarea name="description" id="id_description" class="profile-data-input bio-input form-control"></textarea>
        </div>
    </form>
</div>

Nestor/templates/applicant/VirtualCV/reference_edit.html
{% load static %}
<div class="black_block hidden" id="reference/edit/{{ reference.reference_id }}">
    <form class="form form-horizontal" method="POST"  action="applicant/reference_edit">
        {% csrf_token %}
        <input type="hidden" name="reference_id" value="{{ reference.reference_id }}">
        <input type="submit" class="edit-button" value="Update" />
            <div class="horizontal-input">
        <div class="profile-data-block-three">
            <p class="profile-data-label">Full name</p>
            <input type="text" name="name" class="profile-data-input" value="{{ reference.reference.name }}" required id="id_name">
        </div>
        <div class="profile-data-block-three">
            <p class="profile-data-label">Company</p>
            <input type="text" name="workplace_name" class="profile-data-input" value="{{ reference.reference.workplace_name }}" required id="id_workplace_name">
        </div>

        <div class="profile-data-block-three">
            <p class="profile-data-label">Role</p>
            <input type="text" name="role" class="profile-data-input" value="{{ reference.reference.role }}" required id="id_role">
        </div>
        </div>
            <div class="horizontal-input">
        <div class="profile-data-block-three">
            <p class="profile-data-label">Email</p>
            <input type="text" name="email" class="profile-data-input" value="{{ reference.reference.email }}" required id="id_email">
        </div>
        
        <div class="profile-data-block-three">
            <p class="profile-data-label">Phone</p>
            <input type="text" name="phone" class="profile-data-input" value="{{ reference.reference.phone }}" required id="id_phone">
        </div>
        <div class="profile-data-block-three flex-bottom flex">
            <input type="checkbox" name="is_contactable" class="profile-data" id="id_is_contactable" {% if reference.reference.is_contactable %}checked{% endif %}>
            <p>Ask me before contacting</p>
        </div>
        </div>
    </form>
</div>

Nestor/templates/applicant/VirtualCV/reference_new.html
{% load static %}
<div class="black_block hidden" id="reference/new">
    <form class="form form-horizontal" method="POST" action="applicant/reference_add">
        {% csrf_token %}
        <div class="horizontal-input">
            <input type="submit" class="edit-button" value="Add" />
        </div>
        <div class="horizontal-input">
            <div class="profile-data-block-three">
                <p class="profile-data-label">Full name</p>
                <input type="text" name="name" class="profile-data-input" required id="id_name">
            </div>
            <div class="profile-data-block-three">
                <p class="profile-data-label">Company</p>
                <input type="text" name="workplace_name" class="profile-data-input" required id="id_workplace_name">
            </div>
            <div class="profile-data-block-three">
                <p class="profile-data-label">Role</p>
                <input type="text" name="role" class="profile-data-input" required id="id_role">
            </div>
        </div>        
        <div class="horizontal-input">
            <div class="profile-data-block-three">
                <p class="profile-data-label">Email</p>
                <input type="text" name="email" class="profile-data-input" required id="id_email">
            </div>
            <div class="profile-data-block-three">
                <p class="profile-data-label">Phone</p>
                <input type="text" name="phone" class="profile-data-input" required id="id_phone">
            </div>
            <div class="profile-data-block-three flex-bottom flex">
                <input type="checkbox" name="is_contactable" class="profile-data" id="id_is_contactable">
                <p>Ask me before contacting</p>
            </div>
        </div>
    </form>
</div>

Nestor/templates/applicant/VirtualCV/skills_edit.html
{% load static %}
<div class="black_block hidden" id="skills/edit">
    {% for genre, skills in applicant_skills.items %}
    <div class="black_block_white_subsection">
        <h3>{{ genre }}</h3>
        <div class="skills-container">
            {% for skill in skills %}
            <div class="skill_selection">
                <h4>{{ skill }}</h4>
            </div>
            {% endfor %}
            <div class="new-skill">
                <form class="form form-horizontal flex new-skill-container" method="post" action="applicant/add_skill">
                    {% csrf_token %}
                    <select name="{{ genre.name }}" class="skill-select" required id="id_skill">
                        <option value=""></option>
                        {% for all_genre, all_skill in all_skills.items %}
                        {% if all_genre == genre %}
                {% for a_skill in all_skill %}
                <option value="{{ a_skill }}">{{ a_skill.name }}</option>
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                    </select>
                    <input type="submit" value="+" id="add_skill_select" class="add-skill" src="{% static 'images/plus_icon.png' %}">
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>